### ISSUE TITLE
Should not return  NOT_VALIDATED if callerSearchBase is invalid

### ISSUE THREAD

**Issue by wxwesther** [javaee/security-soteria#127]
Below cases, IMHO, case1 is not expected. And case2, case3 are expected.  Please check.

Case1: callerSearchBase is invalid, then NOT_VALIDATED instead of INVALID returns
```
@LdapIdentityStoreDefinition(
	    url = "ldap://localhost:11389/",
	    callerBaseDn = "ou=caller,dc=securityapi,dc=net",
	    bindDn = "uid=ldap,ou=apps,dc=securityapi,dc=net",
	    bindDnPassword = "changeOnInstall",
        callerSearchBase = "ou=invalid,dc=securityapi,dc=net",
        callerSearchFilter = "(&(uid=%s)(objectClass=person))",
        groupSearchBase = "ou=group,dc=securityapi,dc=net",
        callerNameAttribute = "uid",
        groupNameAttribute = "cn",
        groupMemberAttribute = "member",
        priority=100
)
```

Case2: INVALID returns if callerBaseDn  is INVALID. This is expected
```
@LdapIdentityStoreDefinition(
		url = "ldap://localhost:11389/",
	    callerBaseDn = "ou=invalid,dc=securityapi,dc=net",
	    groupSearchBase  = "ou=invalid,dc=securityapi,dc=net"	    
)
```
Case3) INVALID returns if callerNameAttribute is INVALID.

```
@LdapIdentityStoreDefinition(
	    url = "ldap://localhost:11389/",
	    callerBaseDn = "ou=caller,dc=securityapi,dc=net",	    
        callerNameAttribute = "invalid",
        groupNameAttribute = "cn",
        groupMemberAttribute = "member",
        priority=100
)
```

**Comment by ggam** [comment]
Thanks for reporting this. Could you please provide us an ldiff to run the tests?

**Comment by wmhopkins** [comment]
@wxwesther -- All cases of invalid configuration should cause an exception to be thrown. The three status values are used only for "normal" processing with a valid configuration:

- _VALID_ means the credentials were validated successfully
- _INVALID_ means the credentials were validated but the validation did not succeed -- user not found, bad password, etc.
- _NOT_VALIDATED_ mean that validation was not even attempted, because no `IdentityStores` were configured, or because none of the configured `IdentityStores` handles the type of `Credential` that was provided.

All of those cases represent normal processing, not error cases. Error cases include bad configuration, network errors, etc., and cause an exception to be thrown.

Closing this as **not a bug**.

**Comment by zjmtlab** [comment]
The ldif is like this, please let us know if need more, thanks!

dn: ou=caller,dc=securityapi,dc=net
objectclass: top
objectclass: organizationalUnit
ou: caller

dn: uid=tom,ou=caller,dc=securityapi,dc=net
objectclass: top
objectclass: uidObject
objectclass: person
uid: tom
cn: Tom Rahman
sn: Tom
userPassword: secret1

**Comment by wmhopkins** [comment]
@zjmtlab -- I think our updates crossed each other. Thanks for providing this information, but I have closed this issue based on my comments above.
