### ISSUE TITLE
The SecurityContext.getCallerPrincipal() return null when set a application principal in HAM

### ISSUE THREAD

**Issue by zjmtlab** [javaee/security-soteria#133]
I pass a Application principal to httpMessageContext.notifyContainerAboutLogin() after authentication success.  Then in Servlet, the SecurityContext.getCallerPrincipal() return null
I think this maybe a bug, please confirm, thanks!

            if (result.getStatus() == VALID) {
                
                return httpMessageContext.notifyContainerAboutLogin(
                        new TestPrincipal(result.getCallerPrincipal().getName()), result.getCallerGroups());
            }

**Comment by ggam** [comment]
Hi, indeed seems like a bug :) Could you please provide us a simple reproducer application? This will help us to find it faster

**Comment by arjantijms** [comment]
Also important, please tell us which server you are using and which version etc. Thx!

**Comment by zjmtlab** [comment]
The server I use is glassfish 5.0

**Comment by ggam** [comment]
Could you please provide us some code so we can test it in similar conditions?

I'm using a custom principal right now on my application, similar to your snippet (on Payara 4.1.2.172) ant it works.

**Comment by zjmtlab** [comment]
Thanks for help check it!
The HAM code:
public class TestAuthenticationMechanism implements HttpAuthenticationMechanism {
    
    @Inject
    private IdentityStoreHandler identityStoreHandler;
    
	@Override
	public AuthenticationStatus validateRequest(HttpServletRequest request, HttpServletResponse response, HttpMessageContext httpMessageContext) throws AuthenticationException {
		
		if (request.getParameter("name") != null && request.getParameter("password") != null) {

            String name = request.getParameter("name");
            Password password = new Password(request.getParameter("password"));

            CredentialValidationResult result = identityStoreHandler.validate(
                new UsernamePasswordCredential(name, password));

            if (result.getStatus() == VALID) {
                
                return httpMessageContext.notifyContainerAboutLogin(
                        new TestPrincipal(result.getCallerPrincipal().getName()), result.getCallerGroups());
            }
                
            return httpMessageContext.responseUnauthorized();
        }

        return httpMessageContext.doNothing();
	}

}

The Servlet code:
@DeclareRoles({"Administrator", "Manager", "Employee"})
@WebServlet("/servlet")
@ServletSecurity(@HttpConstraint(rolesAllowed = "Administrator"))
public class Servlet extends HttpServlet {

    private static final long serialVersionUID = 1L;
    
    @Inject
    private SecurityContext securityContext;

    @Override
    public void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {

        PrintWriter writer = response.getWriter();
        
        String contextName = null;
        if (securityContext.getCallerPrincipal() != null) {
            contextName = securityContext.getCallerPrincipal().getName();
        }
        
        writer.write("context username: " + contextName + "\n");
    }

}

The TestPrincipal class:
public class TestPrincipal implements Principal {
    
    private final String name;
    
    public TestPrincipal(String name) {
        this.name = name;
    }
    
    @Override
    public String getName() {
        return name;
    }

}

**Comment by ggam** [comment]
Thanks for the code example! I'll take a look at it later. Just one more question, have you defined any identitystore? Via @DatasourceIdentityStoreDefinition, @LdapIdentityStoreDefinition or by creating a custom one.

**Comment by zjmtlab** [comment]
Yes, I have a identitystore.  I think it not my identitystore issue because it worked fine in other tests.

**Comment by ggam** [comment]
I'm seeing a similar behavior here, with `SecurityContext#getCallerPrincipal()` returning null in case a custom principal was set.

The offending code is in [`SubjectParser#doGetCallerPrincipalFromPrincipals()`](https://github.com/javaee/security-soteria/blob/master/impl/src/main/java/org/glassfish/soteria/authorization/spi/impl/SubjectParser.java#L459), which detects the caller principal based on the class name, searching for common ones.

Looking at the code, one of the recognized classes is `javax.security.enterprise.CallerPrincipal`. You could just use that class for now if it works for you. Instead of thas class name check, we should better check with `Class.isAssignableFrom()`. @arjantijms what do you think?

**Comment by arjantijms** [comment]
This is one of the difficult cases indeed, related to the recent changes.

Before we compromised for Weblogic's issues you could only return a `CallerPrincipal`, so any custom principal had to be a sub-type of that. Indeed, `Class.isAssignableFrom()` would be better anyway, but next to that it probably needs to be aware of how a specific server wraps the custom principal.

We did talk about exactly this issue during the last EG call; JASPIC and the `CallerPrincipalCallback` are flexibel enough so no changes from our side are needed, but for `SecurityContext#getCallerPrincipal()` and variants container specific code is needed (essentially the inverse of the `CallerPrincipalCallback` -> the ability to extract the `CallerPrincipal` from the `Subject` instead of putting it into it.)

I'll meditate a little over this and will try to work on this soon.

**Comment by wmhopkins** [comment]
I think there are two basic approaches. First is to simply delegate to the existing methods in each container (`HttpServletRequest.getUserPrincpal()`, etc.), but that requires being aware of the container you're executing in, obtaining the appropriate object, and delegating to it. The other approach would be a platform-specific SPI, since only the platform knows what bit of magic it's doing to represent the caller and/or return the appropriate principal.

**Comment by arjantijms** [comment]
>The other approach would be a platform-specific SPI, since only the platform knows what bit of magic it's doing to represent the caller and/or return the appropriate principal.

Indeed, that's what I mentioned during the call as well. Incidentally, such a "subject reader" was at some point discussed for this JSR, but eventually nothing was done for it.

The idea was though that while Subject remains a block box, you'd have standard readers and writers for it. The CallerPrincipalCallback is, in a way, a writer for Subject. But there's no corresponding reader.

**Comment by wmhopkins** [comment]
The reader is the getCallerPrincipal() method, what's missing here is the platform integration. I think we can provide a SPI as part of the RI, it doesn't need to be part of the standard because it's an internal issue for each server, and implementations the standard may or may not use the RI.

**Comment by ggam** [comment]
A container SPI with a default implementation using the current strategy (with some enhacenements, like the `isAssignableFrom()`, maybe some `request.getUserPrincipal()`, etc) would work I think.
That SPI could be standarized in a future version if it's too late now.

**Comment by arjantijms** [comment]
>The standard/public reader is the getCallerPrincipal() method;

More or less indeed, but the reader/writers we had in mind would actually work directly on a given `Subject` instance. So in that regard even the `CallerPrincipalCallback` is not a true direct writer.

**Comment by arjantijms** [comment]
>That SPI could be standarized in a future version if it's too late now.

Certainly too late to standardise the SPI. In practice though most SPIs of that kind are product (impl) specific anyway. CDI for instance has a ton of them and they are all Weld or OWB specific.

**Comment by ggam** [comment]
@arjantijms do you think we can start by improving the current algorithm to check for subclasses? That code could be reused as the "default" strategy when the SPI is done. Or are you already working on the SPI part?

**Comment by arjantijms** [comment]
You can already add checks for subclasses if you want.

The SPI part technically is not constrained to the spec release as it's an impl detail that can be done later. Still nice to have it done now of course ;)

I think simplest is just jar service loader with the current reflection one as fallback. For the tests the Arquillian profiles can include example SPI implementations per server.

**Comment by ggam** [comment]
> You can already add checks for subclasses if you want.

I'll take care of this for the moment.

**Comment by ggam** [comment]
@zjmtlab Could you please try with my PR #140? It works for me now.
