### ISSUE TITLE
Future feature request: Allow override of context protected by auth mechanism

### ISSUE THREAD

**Issue by mjremijan** [javaee/security-soteria#190]
In JASPIC, in the @WebListener where you use the AuthConfigFactory to register an AuthConfigProvider, the registerConfigProvider() method allowed you to set the webapp context to protect:

factory.registerConfigProvider(
            new TestSecurityAuthConfigProvider(),
            "HttpServlet",
            "my-testapp",   // <- webapp context to protect
            "The test"
        );

If the parameter value is null, it protects all WAR files deployed to that server.  Alternatively, providing a webapp context protects just that webapp.

This is a really nice feature, especially in an enterprise environment where I will have multiple applications or microservices deployed to the same EE server which all need to be protected in the same way.  This feature is also really nice because it means I can remove the authorization mechanics details from the each application and consolidate it in 1 place.  

I think this a useful feature to bring back into Security API.  Maybe a new annotation which can be put on the authentication mechanism implementation class?  Be able to specify null (all contexts),  a string[] for multiple environments if the webapp context names are known, and maybe a java.util.regex.Pattern attribute for matching multiple contexts.

**Comment by wmhopkins** [comment]
@mjremijan -- there's really nothing to "bring back" -- the behavior of the JASPIC `AuthConfigFactory` is unchanged, and the new Security API is not replacing JASPIC, it's simply building on it to provide a new set of APIs/SPIs.

Making the JSR-375 `HttpAuthenticationMechanism` "global" is not practical at a basic level, because, while the JASPIC `AuthConfigFactory` is a JVM-wide object, the CDI beans defined/used by the new API are, by definition, targeted at some CDI scope. The broadest scope I'm aware of (I haven't reviewed the CDI 2.0 spec) is `@ApplicationScoped`, which is roughly equivalent to the application context that JASPIC references.

In theory, one could provide some server- or container-wide configuration that would tell the container to make the same `HttpAuthenticationMechanism` available to all applications. The spec, in fact, allows for that as a proprietary extension, but does not require implementations to support it. Note that the implementation would need to be done at a level above CDI, likely with the assistance of a proprietary CDI extension, and would require that the specified `HttpAuthenticationMechanism` (and any dependencies) be made available in a bean archive that is visible to every application -- i.e., it couldn't be an `HttpAuthenticationMechanism` that is deployed in an application archive.

I'm closing this issue, as it's more of a spec issue than a reference implementation issue, and the only unresolved point, as I understand the request, is whether the "container-wide" behavior should be specified as MUST rather than MAY. You should feel free to create a new issue in the security-spec repo to track this, and the EG will consider it for a future revision, but I don't expect that we'd end up changing the existing language.

**Comment by ggam** [comment]
Leaving technical difficulties aside I think this is a valid request.

Keep in mind that the RI may provide extensions to the spec and so Soteria
could support this on a propietary basis so we can experiment with it for
future revisions of the spec (if we implement it and find it useful).

I'd reopen the issue so at least there's a record that someone would find
that feature useful. We could then evaluate.

**Comment by wmhopkins** [comment]
Again, I think this is a spec issue. The RI can't usefully address it, as the necessary configuration would need to be at the server/platform level, and, as a result, would be proprietary for each platform. There is no reasonable way for us to implement this in a platform-agnostic manner, as there is no platform-agnostic configuration mechanism. The configuration would need to be at the container/server level, as it is not reasonable for the configuration of a single application to have effect over all other applications deployed in the same container.

I agree that the basic ask is reasonable, which is why I argued for the existing spec language that allows the container to override an application's choice of `HttpAuthenticationMechanism` if desired. But I don't think the spec should mandate this and I see no reasonable way for the RI to implement it.

**Comment by ggam** [comment]
El mié., 30 de agosto de 2017 21:39, Will Hopkins <notifications@github.com>
escribió:

> Again, I think this is a spec issue. The RI can't usefully address it, as
> the necessary configuration would need to be at the server/platform level,
> and, as a result, would be proprietary for each platform. There is no
> reasonable way for us to implement this in a platform-agnostic manner, as
> there is no platform-agnostic configuration mechanism. The configuration
> would need to be at the container/server level, as it is not reasonable for
> the configuration of a single application to have effect over all other
> applications deployed in the same container.
>
So you think that feature from JASPIC is also not reasonable? ;)

**Comment by wmhopkins** [comment]
> So you think that feature from JASPIC is also not reasonable? ;)

Honestly, I'm not fond of JASPIC's `AuthConfigFactory` and the contract it presents, as it provides no standard declarative syntax, the required permission is not sufficiently granular, and it is not amenable to providing consistent, reliable management via configuration at the system/container level. (Nor, as an aside, does it provide sufficient flexibility to support registering different `AuthConfigProviders` for different tenants in a multi-tenant environment.)

The trouble is that it's a programmatic API, and the last caller always wins, making it essentially impossible to write code that can reliably and deterministically ensure that a given `AuthConfigProvider` is registered for any context. At best, you can write code that polls for changes and re-registers the desired provider if it's ever unregistered. Also, an application with sufficient permission can make a call to register an `AuthConfigProvider` for all application contexts. The only scenario in which I would consider that a "feature" rather than a "bug", is if the application in question is some sort of provisioning or management application. It should not be the case that an "ordinary" app can affect the environment or configuration for other ordinary apps, especially as it relates to security. If the necessary permission had sufficient granularity -- if it could be granted for a specific set of contexts, but not for others -- then it would at least be possible to grant an app, or a group of apps, the ability to configure their own JASPIC providers, without placing every other deployed app at the mercy of whatever provider an app might decide to register globally. But as it stands, permission to register a provider for one app context implies permission to register a provider for all app contexts. That seems ungood to me.

In the case of JSR-375, specifically, our whole programming model is built around CDI, and CDI has no global scope -- so any attempt to define global behaviors seems unidiomatic at best. We could, of course, choose to register our `AuthConfigProvider`, and the `HttpBridgeServerAuthModule` it hosts, globally, or for some specific set of app contexts. But would that be the right thing to do? We don't require permissions to declare/deploy a HAM, so registering the bridge SAM globally would allow an application with no special permissions to affect the security configuration of other apps -- at least the JASPIC API requires the caller to have a specific permission. Also, let's say we did register the bridge SAM in all contexts -- how do we know there will be a HAM available for the bridge SAM to invoke in all application contexts? It can't be deployed globally, because there is no global CDI context, and, even if there were, there would likely be classloading problems with trying to globally deploy a HAM that was provided in an application archive. Also, deploying our bridge SAM globally would not be sufficient to ensure that all apps used the same HAM, which is presumably the point of trying to configure it globally. The bridge SAM simply asks CDI for a bean that implements `HttpAuthenticationMechanism`. It doesn't ask for a specific name or implementation class, and the available HAM might therefore be different in each application context.

The only viable way for this to work is if the HAM is provided at the system level, made visible to all app contexts via a shared bean archive, and if a CDI extension is used to ensure that the specified HAM, and no other, is registered in an appropriate CDI scope for every application. That implies system level configuration, not application configuration, and therefore implies a proprietary extension, since Java EE is by nature app-centric, and does not specify how container- or server-wide configuration is done.
