### ISSUE TITLE
Hashing for Database Identity Store

### ISSUE THREAD

**Issue by sbaeurle** [javaee/security-soteria#48]
Hey Guys,

thanks again for your help dealing with the security API.

I added the majority of the already existing Hashing Algorithms to the DataBase Identity Store.

To deal with more complex hashing methods, I've created a new Annotation @HashDefinition, where you can define the Hashing in more detail.

Therefore I changed the Security API as well as the implementation.

Can you please take a look at the adjustments I did, you can find them in my private repos of the Security API and Soteria and tell me if you can use them 😄 .

Security API: [https://github.com/sbaeurle/security-api/tree/hashing](url)
Implementation: [https://github.com/sbaeurle/soteria/tree/hashing](url)

Best Regards,

Simon Bäurle

**Comment by ggam** [comment]
Hi,

The links are broken. The correct ones seem to be:
API: https://github.com/sbaeurle/security-api/tree/hashing
Implementation: https://github.com/sbaeurle/soteria/tree/hashing

This is an interesting proposal. This JSR is now on its final stage and the EG is trying to consolidate things, so  I'm not sure it's viable to add another annotation of this size to the spec right now.

Aside of that, I'm myself not a big fan of such big annotations. Trying to offer every possible feature from an annotation is impossible and (for me) tends to clutter code.
But what you propose clearly shows that there will be a need to configure more options that the currently offered ones.

What do you think about adding a new attribute to allow vendor specific options? The spec should state that those options are allowed to override the default provided ones, eg:

```
@DataBaseIdentityStoreDefinition(
    callerQuery = "SELECT password FROM users WHERE username = ?",
    options = {
        @Option(name = "org.glassfish.pepper_query", "SELECT * FROM pepper"),
        @Option(name = "org.glassfish.salt_position", "FRONT")
    }
)
```

In a future release with more community feedback, more options could be standarized.

What do you think?

**Comment by ggam** [comment]
Btw, I've posted an email to the EG this morning asking about the behavior when the requested encoding/hashing algorithm is not available. Since you've worked on that area, would you please give your opinion there? https://javaee.groups.io/g/javaee-security-spec/message/81

Note that you first need to join the https://javaee.groups.io/g/javaee group before posting.

Thanks!

**Comment by sbaeurle** [comment]
Hi, first thanks for your reply :)

When I considered how to implement hashing, I encountered some major problems.

1. Since Hashing is such a vital part for secure password storing, nearly all possible Hashing-Algorithms should be supported. Therefore, if you use a String as Identifier you can support new HashingAlgorithms, without changing the Specification of the API.

2. In order to support a large varity of hashing methods, I'm not sure, how it is possible to to this, without some big configuration.

Your Idea with some Vendor Specific Specification sounds good , but you still need to declare what specification is possible, therefore an Annotation would be more standardized in my opinion.

 
Hope to hear soon!

**Comment by keilw** [comment]
@ggam This does not look too different from JPL
`"SELECT password FROM users u WHERE u.username = :name"`

**Comment by ggam** [comment]
@sbaeurle standard properties are better of course, but also need time and consensus and... you'll never be able to support *all* possible options (I'm now thinking in a more general sense that hashing). This is not to say that the spec should not add more hashing options. I think they may be fine, but that still we'll need more options. @arjantijms @wmhopkins what do you think?

@keilw Sorry I don't know exactly what are you referring. Could you please clarify?

**Comment by wmhopkins** [comment]
@ggam Yes, we should probably specify the hashing algorithms that are supported. I'd need to do some research, but IIRC, there are probably only a few algorithms that are both appropriate for use with passwords and still considered reasonably strong. I would suggest not supporting older, weaker algorithms, even though that might leave out some legacy use cases. We should use the standard algorithm names where appropriate.

The other question is whether we want to support two-way encryption in addition to hashing. That's necessary if you want to, e.g., do digest authentication, because you need access to the cleartext password. My vote would be no -- it's a relatively rare use case, it adds more complexity, and IdentityStore doesn't really have support for anything like that. Vendors could always add it to their implementation if they wanted.

I'll do a little research and come back proposal for supported algorithms.

**Comment by ggam** [comment]
Glad to see you had this in mind.

How would vendor specific features be enabled? What do you think about the
options attribute for that?

**Comment by sbaeurle** [comment]
@wmhopkins  I agree with you, that there are only few algorithms that are strong enough to be used in the API, but when you just use the MessageDigest and SecureKeyFactory in Java, you can support a large varity of hashing algorithms. 
Since Hashing Algrotihms develop very fast, it's probably the best to support most of the built in Algorithms, as Java Probably updates the Algorithms in the JDK/JRE.

**Comment by sbaeurle** [comment]
@ggam as I wrote, when you implement Hashing using Java built-in Algorithms, you don't need to adjust the Configuration the Hashing, because Java surely will update and adjust their algorithms to make them safe and string enough :)

**Comment by ggam** [comment]
@sbaeurle FYI Will has started the conversation around this on the mailing list: https://javaee.groups.io/g/javaee-security-spec/topic/proposal_for_password_hashing/5456451

You are welcomed to join :)

**Comment by wmhopkins** [comment]
This issue has been addressed by the `PasswordHash` functionality.
