### ISSUE TITLE
The groups in LdapIdentityStore(useFor PROVIDE_GROUP) is not returned 

### ISSUE THREAD

**Issue by wxwesther** [javaee/security-soteria#78]
I tried below scenario against glassfish m5 

LdapIdentityStore: (useFor getGroup only), priority=100
           use/pwd/group: tom/secret1/Administrator, Manager
           use/pwd/group: emma/secret2/Administrator, Employee
           use/pwd/group: bob/secret3/Administrator 
IdentityStore1:  (useFor both validation and getgroup); priority=1000
          use/pwd/group: tom/secret1/Administrator1, Manager1
          use/pwd/group: emma/secret12/Administrator1, Employee1
          use/pwd/group: bob/secret13/Administrator1 
IdentityStore2:  (useFor getgroup only); priority=200
          use/pwd/group: tom/secret1/Administrator2, Manager2
          use/pwd/group: emma/secret12/Administrator2, Employee2
          use/pwd/group: bob/secret13/Administrator2

Issue: When I request with tom/secret1, Only the groups in IdentityStore1 & IdentityStore2 returned. The group in LdapIdentityStore is not returned. Is this a bug?

**Comment by rdebusscher** [comment]
This is indeed an issue but a very tricky one.

The LDAP is searched but is using the Caller information supplied by IdentityStore 1. So information is not in the format uid=tom,ou=xxx,dc=yyy.

So that is why the groups aren't returned.

**Comment by wmhopkins** [comment]
@rdebusscher -- this behavior actually depends on the ldap configuration now, since, in some cases, the DN will be available and can be utilized -- but assuming it is doing caller based look-up, that doesn't explain the observed behavior in and of itself -- are you implying that the LdapIdentityStore isn't set up correctly (group search parameters) to find groups for tom? Because IdentityStore2 seems to be working.

@wxwesther -- if this is still a problem, can you post the annotation used to configure LdapIdenityStore, and the LDIF used to provision it?

**Comment by zjmtlab** [comment]
The annotation used to configure LdapIdentityStore:
@LdapIdentityStoreDefinition(	
		url = "ldap://localhost:11389/",
		callerBaseDn = "ou=caller,dc=securityapi,dc=net",
		groupSearchBase  = "ou=group,dc=securityapi,dc=net",
		useFor={ValidationType.PROVIDE_GROUPS},
	    priority=100
)

The part of LDIF used to provision it, please tell me if need more:

dn: cn=Administrator,ou=group,dc=securityapi,dc=net
objectclass: top
objectclass: groupOfNames
cn: Administrator
member: uid=tom,ou=caller,dc=securityapi,dc=net
member: uid=emma,ou=caller,dc=securityapi,dc=net
member: uid=bob,ou=caller,dc=securityapi,dc=net

dn: cn=Manager,ou=group,dc=securityapi,dc=net
objectclass: top
objectclass: groupOfNames
cn: Manager
member: uid=tom,ou=caller,dc=securityapi,dc=net

dn: cn=Employee,ou=group,dc=securityapi,dc=net
objectclass: top
objectclass: groupOfNames
cn: Employee
member: uid=emma,ou=caller,dc=securityapi,dc=net

**Comment by wmhopkins** [comment]
Need to update group search to use DN -- either from CredentialValidationResult, or by looking it up.

**Comment by wmhopkins** [comment]
This part annotation config looks wrong:
```
useFor={ValidationType.PROVIDE_GROUPS},
```
I don't think the `{}` should be needed if it's not an EL expression.

**Comment by zjmtlab** [comment]
@wmhopkins , I am not sure about it. Since the useFor is a array. Not a single value.

/**
     * Determines what the identity store is used for
     * 
     * @return The type the identity store is used for
     */
    ValidationType[] useFor() default {VALIDATE, PROVIDE_GROUPS};

**Comment by wmhopkins** [comment]
@zjmtiab -- Right, my mistake.

**Comment by wmhopkins** [comment]
Test is still failing. @zjmtiab provided a reference to the TCK test code to help with analysis:

> The test case I mentioned caused by issue 78 is this:
> FAILED........com/sun/ts/tests/securityapi/idstore/ldap/useforgroup/Client.java#testIdentityStore_ldap_useforgroup
> You can found it in the location $TRUNK/src/com/sun/ts/tests/securityapi/idstore/ldap/useforgroup/

**Comment by zjmtlab** [comment]
After add below two properties in LDAP annotation, the groups in LDAP idstore can be returned. I am not sure whether these two properties are MUST.
callerSearchBase = "ou=caller,dc=securityapi,dc=net",
callerSearchFilter = "(&(uid=%s)(objectClass=person))",

But seems there are unexpected additional sub groups also be returned, so the test still fail, I am checking whether this is test issue.

**Comment by wmhopkins** [comment]
This makes sense, because in order to search groups, we need to use caller's DN; i.e., we search for all groups with filter `(member=<callerDn>)`. So we need the DN.

One way we can get the `callerDn` is if it's in the `CredentialValidationResult`, but if the `IdentityStore` that validated the `Credential` doesn't return the `callerDn`, it's not available there. In that case, we search the directory for the user, so we can get the `callerDn`. To do the search, we need `callerSearchBase` and `callerSearchFilter`.

I don't know why it's returning too many groups, though.

**Comment by zjmtlab** [comment]
I think you can ignore the return too many groups issue, I think it is a test bug, we can fix it in test side.

The only thing confused me is seems the Soteria LDAP test not configure these properties, why they can work?

callerSearchBase = "ou=caller,dc=securityapi,dc=net",
callerSearchFilter = "(&(uid=%s)(objectClass=person))",

**Comment by wmhopkins** [comment]
@zjmtlab -- As discussed on the call today, what's going on is that the `IdentityStore` that did the original credential validation did not add the caller's DN to the `CredentialValidationResult` passed to `getCallerGroups()`, so we need to look up the caller DN in order to do the group search.

The Soteria `LdapIdentityStore` _does_ add `callerDn` to the `CredentialValidationResult` when validating, so it's available later for `getCallerGroups()`, and doesn't have to be looked up again.
