### ISSUE TITLE
Server Exception appears if set invalid property value in LdapIdentiyStore ?

### ISSUE THREAD

**Issue by wxwesther** [javaee/security-soteria#79]
I met two issues when set invalid property values in LdapIdentityStore. (with glassfish m5)
Issue 1)
=================================================
Invalid groupNameAttribute property value specified, NPE error appears in Glassfish server, then  validatation got exception and no result (neither INVALID nor VALID / NOT_INVALIDATED returned)

@LdapIdentityStoreDefinition(
url = "ldap://localhost:11389/",
callerBaseDn = "ou=caller,dc=securityapi,dc=net",
baseDn = "uid=ldap,ou=apps,dc=securityapi,dc=net",
password = "changeOnInstall",
searchBase = "ou=caller,dc=securityapi,dc=net",
searchExpression = "(&(uid=%s)(objectClass=person))",
groupBaseDn = "ou=group,dc=securityapi,dc=net",
callerNameAttribute = "uid",
groupNameAttribute = "invalid",
groupCallerDnAttribute = "member",
priority=100
)

[2017-06-15T03:06:01.004-0700] [glassfish 5.0] [SEVERE] [] [] [tid: _ThreadID=26 _ThreadName=Thread-9] [timeMillis: 1497521161004] [levelValue: 1000] [[
java.lang.NullPointerException 
at org.glassfish.soteria.identitystores.LdapIdentityStore.get(LdapIdentityStore.java:294) 
at org.glassfish.soteria.identitystores.LdapIdentityStore.retrieveGroupInformation(LdapIdentityStore.java:229) 
at org.glassfish.soteria.identitystores.LdapIdentityStore.checkThroughSearch(LdapIdentityStore.java:148) 
at org.glassfish.soteria.identitystores.LdapIdentityStore.validate(LdapIdentityStore.java:98) 
at org.glassfish.soteria.identitystores.LdapIdentityStore.validate(LdapIdentityStore.java:87)

Issue 2
=================================================
  Invalid searchbase property value specified, NameNotFoundException exception appears in Glassfish m5 server.  then validatation got exception and no result (neither INVALID nor VALID/NOT_INVALIDATED returned)
@LdapIdentityStoreDefinition(
url = "ldap://localhost:11389/",
callerBaseDn = "ou=caller,dc=securityapi,dc=net",
baseDn = "uid=ldap,ou=apps,dc=securityapi,dc=net",
password = "changeOnInstall",
searchBase = "ou=invalid,dc=securityapi,dc=net",
searchExpression = "(&(uid=%s)(objectClass=person))",
groupBaseDn = "ou=group,dc=securityapi,dc=net",
callerNameAttribute = "uid",
groupNameAttribute = "cn",
groupCallerDnAttribute = "member",
priority=100
)

[2017-06-15T03:06:43.272-0700] [glassfish 5.0] [SEVERE] [] [] [tid: _ThreadID=24 _ThreadName=Thread-9] [timeMillis: 1497521203272] [levelValue: 1000] [[
java.lang.IllegalStateException: javax.naming.NameNotFoundException: [LDAP: error code 32 - The search base entry 'ou=invalid,dc=securityapi,dc=net' does not exist]; remaining name 'ou=invalid,dc=securityapi,dc=net' 
at org.glassfish.soteria.identitystores.LdapIdentityStore.search(LdapIdentityStore.java:288) 
at org.glassfish.soteria.identitystores.LdapIdentityStore.searchCaller(LdapIdentityStore.java:164) 
at org.glassfish.soteria.identitystores.LdapIdentityStore.checkThroughSearch(LdapIdentityStore.java:127) 
at org.glassfish.soteria.identitystores.LdapIdentityStore.validate(LdapIdentityStore.java:98) 
at org.glassfish.soteria.identitystores.LdapIdentityStore.validate(LdapIdentityStore.java:87) 
at sun.reflect.GeneratedMethodAccessor149.invoke(Unknown Source)

BTW, if I set other properties invalid, eg: invalid callerNameAttribute, INVALID would returned for the validation.

**Comment by rdebusscher** [comment]
Thx for these bug reports.

Fix is made available in PR.

Merge will be performed when CI Tests are OK.

**Comment by arjantijms** [comment]
CI tests cleared, thanks Rudy!

**Comment by rdebusscher** [comment]
Issue 1 -> There is a log message (Warning level) to indicate the incorrect name of the _groupNameAttribute_ and it returns an empty set. So that authorization will fail probably later on.

Issue 2 -> Return of NotValidatedResult because IndentityStore was unable to perform the validation of the credentials.

**Comment by wxwesther** [comment]
Issue 3 : Similar exception appears as Issue2 when invalid groupBaseDn specified 
@LdapIdentityStoreDefinition(
url = "ldap://localhost:11389/",
callerBaseDn = "ou=caller,dc=securityapi,dc=net",
groupBaseDn = "ou=invalid,dc=securityapi,dc=net"
)
[2017-06-19T21:26:49.183-0700] [glassfish 5.0] [SEVERE] [] [] [tid: _ThreadID=26 _ThreadName=Thread-9] [timeMillis: 1497932809183] [levelValue: 1000] [[
java.lang.IllegalStateException: javax.naming.NameNotFoundException: [LDAP: error code 32 - The search base entry 'ou=invalid,dc=securityapi,dc=net' does not exist]; remaining name 'ou=invalid,dc=securityapi,dc=net' 
at org.glassfish.soteria.identitystores.LdapIdentityStore.search(LdapIdentityStore.java:276) 
at org.glassfish.soteria.identitystores.LdapIdentityStore.retrieveGroupInformation(LdapIdentityStore.java:218) 
at org.glassfish.soteria.identitystores.LdapIdentityStore.checkDirectBinding(LdapIdentityStore.java:196) 
at org.glassfish.soteria.identitystores.LdapIdentityStore.validate(LdapIdentityStore.java:96) 
at org.glassfish.soteria.identitystores.LdapIdentityStore.validate(LdapIdentityStore.java:87)

**Comment by wmhopkins** [comment]
@arjantijms , @rdebusscher : Reopening this as it seems like the wrong fix.

My recollection from earlier discussions about the `IdentityStore` status values, and the extent to which we did or didn't need a fourth status to indicate a processing error, is that we decided not to create a fourth status value, and that `IdentityStores` should throw exceptions for processing errors, which presumably include config issues as well as things like network errors. Unfortunately, the spec does not say this explicitly, but the description of _NOT_VALIDATED_ is fairly specific, and includes only the case that an `IdentityStore` doesn't attempt validation because it doesn't handle the `Credential` type.

I attempted to start an email discussion on this point a few days ago, but got no response, and need to ensure that the RI behavior is reasonable and consistent for all built-in `IdentityStores`. Reopening this issue to change the resolution from returning _NOT_VALIDATED_ to throwing an exception.

**Comment by rdebusscher** [comment]
Throwing an exception is fine for me. But maybe it isn't something the developer expects. 

This issue was opened because there was an exception when an invalid property value was specified and not returning one of the enum states.

If using an exception, best a specific exception like InvalidPropertyException (which should be defined at API level) to clearly indicate what is wrong.

But that isn't probably possible anymore.

**Comment by wmhopkins** [comment]
@rdebusscher --

Exactly. The spec is frozen, and it doesn't say anything about exceptions. Ideally, we'd add some new statuses or checked exceptions to the API, but at the moment we have to decide what to do given the current state of the spec.

To me, it seems the only options we really have are:
- Unchecked exceptions -- Developers may not expect unchecked exceptions, but if this is the behavior of the RI, they'll likely adjust rapidly. :-) The resulting code will be easy to adapt to checked exceptions in the future.
- Overload the _NOT_VALIDATED_ status -- This is actually contrary to what the spec _does_ say about the meaning of _NOT_VALIDATED_, and it locks us in to supporting the overloaded usage forever. Moreover, if this is the approach, it will be a lot more difficult to adapt code to any new statuses or exceptions we might define in an MR, since code written to expect _NOT_VALIDATED_ for all cases other than _VALID/INVALID_ cannot be distinguishing between "`Credential` type not supported" and actual runtime errors.

There are really no good answers, but given the available choices, unchecked exceptions seem the better choice to me.

**Comment by wmhopkins** [comment]
Updated `LdapIdentityStore` to ensure consistent exception handling. Where possible to detect, `IdentityStoreConfigurationExceptions` are thrown; if not, and if an error results, an `IdentityStoreRuntimeException` is thrown.
